### ISSUE TITLE
When the accumulator is not communicating with nozzle it should return a 500

### ISSUE THREAD

**Issue by poy** [cloudfoundry/noisy-neighbor-nozzle#13]
The accumulator returns a 404 if it is not communicating with the nozzle. This leads to confusion as users assume they have done something wrong in their request when really the configuration is at fault.

**Comment by thepeterstone** [comment]
We ran into this issue as a result of deployment issues. We've improved the deploy process to avoid this particular problem but are not currently planning to fix the underlying issue.
