### ISSUE TITLE
Missing info on app generating noise

### ISSUE THREAD

**Issue by findneville** [cloudfoundry/noisy-neighbor-nozzle#15]
When doing log noise, it shows an app that is generating a lot of noise but it is missing org/space information and the app does not exist in the CF foundation. The other results all show the proper org.space.app/instance format except for this one. 

Any pointers on how to troubleshoot this? 

user } (~) cf log-noise
Volume Last Minute  App Instance
2,916,850           be14c347-788f-4e83-ad35-89bf3a0ab00f/1

user } (~) cf curl /v2/apps/be14c347-788f-4e83-ad35-89bf3a0ab00f
{
   "description": "The app could not be found: be14c347-788f-4e83-ad35-89bf3a0ab00f",
   "error_code": "CF-AppNotFound",
   "code": 100004
}

**Comment by MasslessParticle** [comment]
It's possible that the app has been deleted or that something that's not an app is emitting logs with a guid as a source id.

Do you have LogCache installed? If so, you can use the `meta` and `read` endpoints or the LogCacheCLI to look at the logs being emitted by that source and better understand where they're coming from. 

Additionally, you could connect to the RLP using [this tool](https://github.com/cloudfoundry-incubator/loggregator-tools/blob/master/rlpreader/main.go) and see if that source's logs tell you anything. It needs to be copied to the log-api vm and you can use the RLP's certs to make the connection.
