### ISSUE TITLE
Secret Key rotation?

### ISSUE THREAD

**Issue by jdm019000** [cloudfoundry/noisy-neighbor-nozzle#17]
Is there some setting that is causing the secret key to rotate or be changed.  It seems every week the nn-nozzle app fails due to bad key authentication.  I am also not able to use the key i set from the command line when i created the uaac client.  The key is in the app as environment variable. Something is changing it at the command line i suppose but not updating the application.

Any insight to this would be helpful.

**Comment by MasslessParticle** [comment]
What do you mean that the key is invalid? We use a client id and secret for to communicate with the foundation, is that becoming invalid?

**Comment by jdm019000** [comment]
Correct.  Something is changing the secret key for the client i made for the tool.  I am also not able to reset the secret because i need to changed secret in order to reset it.   I have been deleting the client and adding the client back with the same key I used the first time.  Then i restage the app and it works again.

**Comment by MasslessParticle** [comment]
I see, the Noisy Neighbor Nozzle does not change any UAA secrets. It only uses the provided client/secret to fetch tokens. This is an issue with your UAA administration or configuration

**Comment by jdm019000** [comment]
Okay well this is odd because it is only occurring with this app and plugin.  I am not having any other issues with uaac, which is why it makes me think its your code.  I have opened up a Pivotal Case on this issue.
Case 205194. I am waiting for it to fail again due to bad secret.
